### ISSUE TITLE
The API didn't return a track stream URL.

### ISSUE THREAD

**Issue by Prohibitive** [Sorrow446/LivePhish-Downloader#1]
Windows 11 
lp_dl_x64.exe

C:\Users\Administrator\Downloads\livephish>lp_dl_x64.exe https://plus.livephish.com/#/catalog/recording/255
 __    _         _____ _   _     _      ____                _           _

|  |  |_|_ _ ___|  _  | |_|_|___| |_   |    \ ___ _ _ _ ___| |___ ___ _| |___ __
_
|  |__| | | | -_|   __|   | |_ -|   |  |  |  | . | | | |   | | . | .'| . | -_|
_|
|_____|_|\_/|___|__|  |_|_|_|___|_|_|  |____/|___|_____|_|_|_|___|__,|___|___|_|

Signed in successfully - HiFi Trial with Monthly Subscription

Album 1 of 1:
Phish - 12/31/02 Madison Square Garden, New York, NY
The API didn't return a track stream URL.
The API didn't return a track stream URL.
The API didn't return a track stream URL.
The API didn't return a track stream URL.
The API didn't return a track stream URL.
The API didn't return a track stream URL.
The API didn't return a track stream URL.
The API didn't return a track stream URL.
The API didn't return a track stream URL.
The API didn't return a track stream URL.
The API didn't return a track stream URL.
The API didn't return a track stream URL.
The API didn't return a track stream URL.
The API didn't return a track stream URL.
The API didn't return a track stream URL.
The API didn't return a track stream URL.
The API didn't return a track stream URL.
The API didn't return a track stream URL.
The API didn't return a track stream URL.
The API didn't return a track stream URL.
The API didn't return a track stream URL.
The API didn't return a track stream URL.
The API didn't return a track stream URL.
The API didn't return a track stream URL

i don know. Maybe u help me?
Sorry my english bad.
Thank You

**Comment by Prohibitive** [comment]
@Sorrow446 i wait ur answer Thank u

**Comment by Sorrow446** [comment]
Fixed 3 days ago, just haven't uploaded updated binaries yet.
https://github.com/Sorrow446/LivePhish-Downloader/commit/8fe1a630a7029956dff1fc32cbdc97e1febcd3bb
