### ISSUE TITLE
Failed to get album metadata. invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by Prohibitive** [Sorrow446/LivePhish-Downloader#2]
Windows 11
lp_dl_x64.exe

https://plus.livephish.com/#/catalog/recording/1649
https://plus.livephish.com/#/catalog/recording/1648
https://plus.livephish.com/#/catalog/recording/1647
https://plus.livephish.com/#/catalog/recording/1646

and more..
Thank you
@Sorrow446

**Comment by Sorrow446** [comment]
I'll look into this tonight. Looks like the API returned HTML instead of JSON for some reason.

**Comment by Prohibitive** [comment]
@Sorrow446 Thank you, i wait ur fix.
Good days

**Comment by Sorrow446** [comment]
These albums don't exist. Where did you get the URLs?

**Comment by Prohibitive** [comment]
Yes full siterip, auto generator
https://ctxt.io/2/AADgkAuVEg
@Sorrow446

**Comment by Sorrow446** [comment]
Then you can ignore those errors and carry on.
