### ISSUE TITLE
Invalid URL on all downloads

### ISSUE THREAD

**Issue by JustinAiken** [Sorrow446/LivePhish-Downloader#3]
```bash
$ ./lp_dl_mac_x64 https://plus.livephish.com/index.html\#/catalog/recording/1747

 __    _         _____ _   _     _      ____                _           _
|  |  |_|_ _ ___|  _  | |_|_|___| |_   |    \ ___ _ _ _ ___| |___ ___ _| |___ ___
|  |__| | | | -_|   __|   | |_ -|   |  |  |  | . | | | |   | | . | .'| . | -_|  _|
|_____|_|\_/|___|__|  |_|_|_|___|_|_|  |____/|___|_____|_|_|_|___|__,|___|___|_|

Signed in successfully - HiFi Trial with Yearly Subscription

Album 1 of 1:
Invalid URL: https://plus.livephish.com/index.html#/catalog/recording/1747
```

- This is with [release 2](https://github.com/Sorrow446/LivePhish-Downloader/releases/tag/2)
- I've tried a few different recordings, same message for all.
- Not sure why it says "HiFi Trial", I paid the full $199 
- URL works fine in browser, listening to it now

**Comment by JustinAiken** [comment]
Ahh, I think I see the issue...

The regex matcher doesn't have `index.html` in the URL:
https://github.com/Sorrow446/LivePhish-Downloader/blob/61d5472ed7e9d1e2f2128e7e49499da9f1af4b44/main.go#L42

Browsing around the website, sometimes I see it and sometimes I don't

I think a regex like `https://plus.livephish.com/(index\.html)?#/catalog/recording/(\d+)$` would get both... but I don't know go

**Comment by Sorrow446** [comment]
It has two regexes:
```go
	regexStrings = [2]string{
		`^https://plus.livephish.com/#/catalog/recording/(\d+)$`,
		`^https://www.livephish.com/browse/music/0,(\d+)/[\w-]+$`,
	}
```
Where from the web player are you getting the links? Are you searching for them? index.html is never inserted in my browser.
Your subscription plan is as it's fetched from the API. `HiFi Trial with Yearly Subscription`

**Comment by Sorrow446** [comment]
https://github.com/Sorrow446/LivePhish-Downloader/commit/66fb1305075fba266b4959d06dc330e094cc0e1e
Mac x64 with index URLs support: https://anonfiles.com/t8rcg4key1/lp_dl_mac_x64
Feel free to open another issue if there's any more issues.

**Comment by JustinAiken** [comment]
Thanks!! Got hundreds downloaded now, so much better than praying the app works! 😀

**Comment by Sorrow446** [comment]
You're welcome. Glad it's of use to you.
